// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uef_diem_danh.Database;

#nullable disable

namespace uef_diem_danh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("uef_diem_danh.Models.BuoiHoc", b =>
                {
                    b.Property<int>("MaBuoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBuoiHoc"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LopHocMaLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayHoc")
                        .HasColumnType("date");

                    b.Property<int>("TietHoc")
                        .HasColumnType("int");

                    b.HasKey("MaBuoiHoc");

                    b.HasIndex("LopHocMaLopHoc");

                    b.ToTable("BuoiHoc");
                });

            modelBuilder.Entity("uef_diem_danh.Models.DiemDanh", b =>
                {
                    b.Property<int>("MaDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiemDanh"));

                    b.Property<int>("BuoiHocMaBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("HocVienMaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("BuoiHocMaBuoiHoc");

                    b.HasIndex("HocVienMaHocVien");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("uef_diem_danh.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocVien");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("uef_diem_danh.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ThoiGianBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ThoiGianKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaLopHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("uef_diem_danh.Models.ThamGia", b =>
                {
                    b.Property<int>("MaThamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThamGia"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HocVienMaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("LopHocMaLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.HasKey("MaThamGia");

                    b.HasIndex("HocVienMaHocVien");

                    b.HasIndex("LopHocMaLopHoc");

                    b.ToTable("ThamGia");
                });

            modelBuilder.Entity("uef_diem_danh.Models.BuoiHoc", b =>
                {
                    b.HasOne("uef_diem_danh.Models.LopHoc", "LopHoc")
                        .WithMany("BuoiHocs")
                        .HasForeignKey("LopHocMaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("uef_diem_danh.Models.DiemDanh", b =>
                {
                    b.HasOne("uef_diem_danh.Models.BuoiHoc", "BuoiHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("BuoiHocMaBuoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("uef_diem_danh.Models.HocVien", "HocVien")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("HocVienMaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiHoc");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("uef_diem_danh.Models.ThamGia", b =>
                {
                    b.HasOne("uef_diem_danh.Models.HocVien", "HocVien")
                        .WithMany("ThamGias")
                        .HasForeignKey("HocVienMaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("uef_diem_danh.Models.LopHoc", "LopHoc")
                        .WithMany("ThamGias")
                        .HasForeignKey("LopHocMaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("uef_diem_danh.Models.BuoiHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("uef_diem_danh.Models.HocVien", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("ThamGias");
                });

            modelBuilder.Entity("uef_diem_danh.Models.LopHoc", b =>
                {
                    b.Navigation("BuoiHocs");

                    b.Navigation("ThamGias");
                });
#pragma warning restore 612, 618
        }
    }
}
